sonar.projectKey=EstacaoMeteorologia
sonar.projectName=EstacaoMeteorologia
sonar.projectVersion=1.0

# Conexão com o servidor SonarQube
sonar.host.url=http://host.docker.internal:9000
sonar.token=sqp_855efdcecc51da726df7acc28eda222ce96f5efc

# Define o diretório base (o próprio diretório backend)
sonar.sources=app,routes,resources
sonar.tests=tests

# Exclusões de pastas que não precisam ser escaneadas
sonar.exclusions=vendor/**,node_modules/**,public/**,storage/**,bootstrap/**,database/**,*.js,*.css

# Exclusões para cobertura de testes (arquivos que não precisam ter teste escrito)
sonar.coverage.exclusions=app/Providers/**,app/Http/Middleware/**

# Caminho para relatórios de cobertura de testes (quando você rodar os testes PHPUnit/Jest)
# sonar.php.coverage.reportPaths=build/logs/clover.xml
# sonar.javascript.lcov.reportPaths=coverage/lcov.info
